version: '3.8'

services:
  notebook_db:
    image: mysql:8.0
    container_name: NotebookDB
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_ENV}
      MYSQL_DATABASE: ${MYSQL_DATABASE_ENV}
      MYSQL_USER: ${MYSQL_USER_ENV}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_ENV}
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

  notebook_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NotebookApp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://notebook_db:3306/${MYSQL_DATABASE_ENV}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER_ENV}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD_ENV}
    ports:
      - "8089:8080"
    depends_on:
      - notebook_db

volumes:
  db_data:
